/*
Copyright (c) 2018 Lukasz Figiel
*/

#define LOOKER_WIFI_VAR_COUNT_MAX 64
#define LOOKER_WIFI_VAR_NAME_SIZE 64
#define LOOKER_WIFI_VAR_VALUE_SIZE 64
#define LOOKER_WIFI_VAR_STYLE_SIZE 64

//common
#define LOOKER_MSG_PAYLOAD_SIZE_MAX 61  //61+1+1+1=64
#define LOOKER_MSG_PREFIX (LOOKER_MSG_PAYLOAD_SIZE_MAX + 1)
#define ACK_SUCCESS 0
#define ACK_FAILURE 255

